### ISSUE TITLE
Possible Issues With the Directory Getting Pulled From Github

### ISSUE THREAD

**Issue by DmVigi1** [KenethGarcia/ClassiPyGRB#10]
I tried installing the software several times. However, I believe there is something wrong when the directory is pulled from the GitHub, becausenot even the pip commands were working (ie not creating the directory /ClassiPyGRB). I used the macOSX route and have shared my terminal below as well

 I would really like to use this code so please let me know if there is an issue creating the directory or something I did. Thanks. 

[Pip.pdf](https://github.com/user-attachments/files/16086725/Pip.pdf)
[Git.pdf](https://github.com/user-attachments/files/16086726/Git.pdf)

**Comment by KenethGarcia** [comment]
Hi @DmVigi1 ,

After reading your error description and the PDFs, I figure out that your main problem is related to your installation of ffmpeg on your Mac. Try to install manually this package in your machine an re-try to install ClassiPyGRB.

If you are using a M1-M2 Macbook and you have not any ffmpeg available packages, try to install ClassiPyGRB in a computer with imageio compatibility.

Thanks a lot for the comments!
