### ISSUE TITLE
JOSS: `parallel_lc_limiter` is extremely slow

### ISSUE THREAD

**Issue by dfm** [KenethGarcia/ClassiPyGRB#2]
In [the 3rd tutorial](https://github.com/KenethGarcia/ClassiPyGRB/blob/64305525c9fae77be8d9780ddbf0a3e06aeca9c0/docs/3.BAT_Preprocess.ipynb), it looks like the following line is expected to take approximately 9 seconds:

```python
limited_data, GRB_names, errors = swift.parallel_lc_limiter(GRB_names)
print(errors)
```

But on my computer is takes well over an hour (with some fraction of that time seeming to be spent downloading data). This should be more clearly explained in the tutorial.

ref: https://github.com/openjournals/joss-reviews/issues/5923

**Comment by KenethGarcia** [comment]
Thank you for your comment. The execution time of the light curve limiter function depends on the query time of the data. The 9 seconds mentioned in the tutorials reflect a scenario where data was previously downloaded locally. However, if **ClassiPyGRB** retrieves data directly from the [Swift/BAT website](https://swift.gsfc.nasa.gov/results/batgrbcat/) to limit light curves, the duration can significantly vary based on internet connection speed and server availability. 

We have now included an explanation of this in the tutorials, along with a strong recommendation to download local data if you aim to limit the dataset to a few seconds.

**Comment by dfm** [comment]
This makes sense - thanks for clearing it up in the tutorial!
