### ISSUE TITLE
JOSS: The documentation does not provide a sufficient statement of need

### ISSUE THREAD

**Issue by dfm** [KenethGarcia/ClassiPyGRB#3]
The only documentation is currently the README and the tutorial notebooks. To satisfy the JOSS requirements, the README should explain clearly why this code exists and who the target audience is (a "statement of need").

ref: https://github.com/openjournals/joss-reviews/issues/5923

**Comment by KenethGarcia** [comment]
Thank you for the comment. We already added a section in the README called "Statement of need" where it is specified:

- An introduction to the problem/challenge
- What are the current limitations or gaps
- Benefits of the package
- Relevance to the Community and target audience
- Potential impact
- User scenarios or use cases

**Comment by dfm** [comment]
This is excellent!
