### ISSUE TITLE
JOSS: It's not clear how to run the tests

### ISSUE THREAD

**Issue by dfm** [KenethGarcia/ClassiPyGRB#5]
There appear to be tests implemented in the `tests` directory, but it's not clear how to run them and they're not executed on CI. I'd recommend documenting the test running procedure and adding a GitHub Actions workflow to run the tests.

ref: https://github.com/openjournals/joss-reviews/issues/5923

**Comment by KenethGarcia** [comment]
Thank you for bringing up the concern regarding the tests in the repository. I'm pleased to inform you that we have implemented the following solutions:

1. **Documentation for Test Running Procedure:**
   We have added a documentation section in the repository's README, explaining how to run the tests.

2. **GitHub Actions Workflow for Test Execution:**
   A GitHub Actions workflow has been created to automate the testing process. This workflow is triggered on each push to the repository, and it ensures that the tests are executed in a controlled and consistent environment. You can find the workflow configuration file in the `.github/workflows` directory.

Thank you for your valuable input and collaboration!

**Comment by dfm** [comment]
This is great! I can confirm that I can now easily run all the tests locally and they all pass.
