### ISSUE TITLE
Hardcoded absolute paths in tutorials

### ISSUE THREAD

**Issue by dfm** [KenethGarcia/ClassiPyGRB#6]
In several tutorials (including the TSNE intro), there are hard coded paths of the form `/home/keneth/Documents/ClassiPyGRB/docs/...` used. While it is noted that these should be changed, it seems like it would also be fine to use relative paths (e.g. `animation1.gif`), and I think that would be more generally useful! Not a major blocker, but I always recommend that full paths like these be removed from any code/tutorial that's meant for public consumption.

ref: https://github.com/openjournals/joss-reviews/issues/5923

**Comment by KenethGarcia** [comment]
Thank you for the comment!

Of course, we have not noticed the hardcoded paths in the Tutorial of TSNE Overview. We have changed these paths for simplicity. Moreover, I want to stress that in **ClassiPyGRB**, the saved filename on the *tsne_animation* instance can be any particular or relative path.
