### ISSUE TITLE
Incorrect path in tutorial 11 leads to unexpected crashes

### ISSUE THREAD

**Issue by dfm** [KenethGarcia/ClassiPyGRB#7]
In the `11.Viewer...` tutorial, the first line is:

```python
app = Viewer(root_path='type-your-root-path-here')
```

but I think it should be

```python
app = Viewer(root_path='type-your-path-here')
```

to be consistent with the other tutorials. If this change isn't made, the viewer crashes with data access errors.

**Comment by KenethGarcia** [comment]
Thank you for the issue! We have corrected the path indication. 

Moreover, we want to mention that it is also customizable all the paths inside the Viewer instance, because it shares the same paths as the _SWIFT_ instance inside **ClassiPyGRB**.
