### ISSUE TITLE
Add empty __init__.py to summary_tables folder

### ISSUE THREAD

**Issue by jeqcho** [KenethGarcia/ClassiPyGRB#9]
**Reproduction:**
After running `pip install ClassiPyGRB` and installing all required libraries, run the following python file.

```
from ClassiPyGRB import SWIFT

swift = SWIFT(root_path=r'data', res=64)
```

**Error:**
`FileNotFoundError: 'summary_general.txt' resource not found in 'ClassiPyGRB.summary_tables'`

**Fix:**
It appears that Python ignores the `summary_tables` folder of the library because it does not have `__init__.py` in the folder. Simply add an empty file with this file name to the folder to fix the error.

**Comment by KenethGarcia** [comment]
The necessary change has been implemented! Thank you for bringing this issue to my attention. I will remain vigilant for any future problems that may arise.
